language: java
jdk:
  - openjdk7
script:
  - name=$(date +%Y%m%d)
  - cd /home/travis/build/Neder/BuildTools-Travis
  - "wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar"
  - sudo apt-get install git tar
  - java -jar BuildTools.jar
  - ls
  
after_success:
  - "rm -rf apache-maven*"
  - "rm -rf jacobe*"
  - "tar -cvzf BuildTools_${TRAVIS_JOB_NUMBER}_Returns.tar.gz *"
  - "sudo chmod 777 ./upload.sh"
  - "./upload.sh"